export const FETCH_QUOTES_ATTEMPT = 'FETCH_QUOTES_BEGIN';
export const FETCH_QUOTES_SUCCESS = 'FETCH_QUOTES_SUCCESS';
export const FETCH_QUOTES_FAILURE = 'FETCH_QUOTES_FAILURE';
export const RANDOM_QUOTE_SET = 'RANDOM_QUOTE_SET';
