export const FETCH_QUOTES_BEGIN = 'FETCH_QUOTES_BEGIN';
export const FETCH_QUOTES_SUCCESS = 'FETCH_QUOTES_SUCCESS';
export const FETCH_QUOTES_FAILURE = 'FETCH_QUOTES_FAILURE';
export const RANDOM_QUOTE_GET = 'RANDOM_QUOTE_GET';
